require("leon.plugins-setup")
require("leon.core.options")
require("leon.core.keymaps")
require("leon.core.colorscheme")
require("leon.plugins.comment")
require("leon.plugins.nvim-cmp")
require("leon.plugins.nvim-tree")
require("leon.plugins.lualine")
require("leon.plugins.telescope")
require 'colorizer'.setup()
