#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d sys term www dev txt vid flt spot virt gfx
bspc monitor DVI-0 -d sys term www dev txt

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config single_monocle false

bspc rule -a Gimp desktop='^7' follow=on
# bspc rule -a Alacritty desktop='^2'
bspc rule -a firefox desktop='^3'
# bspc rule -a Geany desktop='^9'
bspc rule -a Spotify desktop='^8'
bspc rule -a virt-manager desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Alacritty:floating state=floating

# Border
bspc config focused_border_color        "#81c8be"
bspc config normal_border_color         "#babbf1"
bspc config active_border_color         "#073642"

#
# Autostart
#
killall firewall-applet

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
killall polybar &
zsh ~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &
# ~/.config/scripts/screen_msg.sh &

# Conky
killall -q conky
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done &
conky -c ~/.config/conky.conf &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
killall picom
picom --config ~/GitHub/config/Files/picom.conf -b --experimental-backends --backend glx --blur-method none --animations --animation-for-open-window zoom --animation-stiffness 300 --vsync &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
# ~/.config/bspwm/scripts/low_bat_notifier.sh
